//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyHoc
    {
        public int ID { get; set; }
        public string NAMHOC { get; set; }
        public Nullable<int> HOCSINH { get; set; }
        public Nullable<int> MONHOC { get; set; }
        public Nullable<int> GIAOVIEN { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }
    
        public virtual GiaoVien GiaoVien1 { get; set; }
        public virtual HocSinh HocSinh1 { get; set; }
        public virtual MonHoc MonHoc1 { get; set; }
    }
    public partial class DangKyHocEntity
    {
        public int ID { get; set; }
        public string NAMHOC { get; set; }
        public Nullable<int> HOCSINH { get; set; }
        public Nullable<int> MONHOC { get; set; }
        public Nullable<int> GIAOVIEN { get; set; }
        public Nullable<System.DateTime> NGAYDANGKY { get; set; }

        public string TenHocSinh { get; set; }
        public string TenGiaoVien { get; set; }
        public string TenMonHoc { get; set; }
    }
}
