//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public MonHoc()
        {
            this.DangKyHocs = new HashSet<DangKyHoc>();
        }
    
        public int ID { get; set; }
        public string TEN { get; set; }
        public Nullable<int> SOTINCHI { get; set; }
    
        public virtual ICollection<DangKyHoc> DangKyHocs { get; set; }
    }
    public partial class MonHocEntity
    {
        public int ID { get; set; }
        public string TEN { get; set; }
        public Nullable<int> SOTINCHI { get; set; }
    }
}
